version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: evaluation-dev
        POSTGRES_PASSWORD: evaluation-dev
        POSTGRES_DB: evaluation
    ports:
      - 5432:5432
//    volumes:
//            - ./sql/tables:/docker-entrypoint-initdb.d/
